name: Actions Workflow

on: [push]

jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v3
      - name: List After Files
        run: |
          pwd
          ls -a    
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Sachin
      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time }}"
